# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# File upload support
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# App name
spring.application.name=prime-vehicle-rentals

# Show FileRepository debug logs in console
logging.level.com.vehiclerental=DEBUG
